config/routes.rb
Rails.application.routes.draw do
  resources :accesses
  resources :links
  devise_for :users
  get 'contact/index'
  get 'about_us/index'
  get "/l/:slug", to: "links#redirect", as: "redirect_link"
  get "/my_links", to: "links#my_links", as: "my_links"
  get "/input_password/:id", to: "links#input_password", as: "input_password"
  post 'links/verify_password/:id', to: 'links#verify_password', as: 'verify_password_link'
  post 'accesses/filtered_accesses', to: 'accesses#filtered_accesses', as: 'filtered_access'
  post 'links/filtered_links', to: 'links#filtered_links', as: 'filtered_link'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "main#index"
end

app/models/access.rb
class Access < ApplicationRecord
  validates :ip, presence: true
  belongs_to :link
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/link.rb
class Link < ApplicationRecord

  # Validaciones
  validates :original_link, presence: true, format: { with: URI::regexp(%w[http https]), message: 'Debe ser una URL con protocolo http o https' }
  validates :slug, presence: true, uniqueness: true, format: { with: /\A[a-zA-Z0-9_-]+\z/, message: 'Solo puede contener letras, numeros y guiones' }
  validates :category, presence: true
  validates :expiration, presence: true, if: -> { category == 'Temporal' }
  validates :password, presence: true, if: -> { category == 'Privado' }

  # Relaciones
  has_many :accesses, dependent: :destroy
  belongs_to :user

  # Acciones previas para generar ShortLinks y Slugs
  before_validation :generate_slug

  def is_accesable?
    if self.category == "Efimero" && self.accesses.any?
      return false
    end
    if self.category == "Temporal" && self.expiration < DateTime.now
      return false
    end
    return true
  end

  def today_access
    self.accesses.where('DATE(created_at) = ?', Date.today).count
  end


  def total_access
    self.accesses.count
  end

  def generate_slug
    # Perdon por hacer trampa, uso un while

    return if slug.present? # Si ya tiene un valor, no genero uno nuevo

    potential_slug = SecureRandom.hex(5)
    while Link.exists?(slug: potential_slug)
      potential_slug = SecureRandom.hex(5)
    end

    self.slug = potential_slug
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :links, dependent: :destroy
  validates :username, presence: true, uniqueness: true
  # validates :email, presence: true, uniqueness: true
end

app/controllers/about_us_controller.rb
class AboutUsController < ApplicationController
  def index
  end
end

app/controllers/accesses_controller.rb
class AccessesController < ApplicationController
  before_action :authenticate_user!, only: %i[ index filtered_accesses search_by_dates ]
  before_action :check_owner, only: %i[ index filtered_accesses search_by_dates ]

  def index
    @accesses = Link.find(params[:format]).accesses
    @link_id = params[:format]
  end

  def filtered_accesses
    @accesses = Link.find(params[:format]).accesses
    if params[:filter_type] == "Por Ip"
      @filtered_accesses = @accesses.where("ip LIKE ?", "%#{params[:ip]}%")
    else
      search_by_dates(params[:fecha_inicio], params[:fecha_fin])
    end
  end

  def search_by_dates(fecha_inicio, fecha_fin)
    fecha_fin = fecha_fin.to_date
    fecha_inicio = fecha_inicio.to_date
    if fecha_inicio.present? && fecha_fin.present?
      @filtered_accesses = @accesses.where(created_at: fecha_inicio..fecha_fin.end_of_day)
    elsif fecha_inicio.present? && fecha_fin.blank?
      @filtered_accesses = @accesses.where('created_at >= ?', fecha_inicio)
    elsif fecha_fin.present? && fecha_inicio.blank?
      @filtered_accesses = @accesses.where('created_at <= ?', fecha_fin.end_of_day)
    else
      @filtered_accesses = @accesses.all
    end

    @filtered_accesses
  end

  private
    def check_owner
      @link = Link.find(params[:format])
      if @link.user_id != current_user.id
        return render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
      end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ show edit update destroy new create ]
  before_action :check_owner, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
    if user_signed_in?
      @links = Link.where.not(user_id: current_user.id)
    end
    @links
  end

  def my_links
    @links = current_user.links
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = current_user.links.build
  end
  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create

    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to links_url, notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to links_url, notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy!

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def redirect
    @link = Link.where(:slug => redirect_params[:slug]).first

    if @link.present?
      if @link.is_accesable?
        if @link.category == "Privado"
          return redirect_to "/input_password/#{@link.id}"
        end
        @link.accesses.create(:ip => request.remote_ip)
        return redirect_to @link.original_link, allow_other_host: true
      end
    end
    return render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
  end

  def filtered_links
    @filtered_links = Link.where("original_link LIKE ?", "%#{params[:ip]}%")
  end

  def input_password
  end

  def verify_password
    @link = Link.find(params[:id])

    if @link.password == params[:password]
      @link.accesses.create(:ip => request.remote_ip)
      return redirect_to @link.original_link, allow_other_host: true
    else
      return redirect_to "/input_password/#{@link.id}"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    def check_owner
      @link = Link.find(params[:id])
      if @link.user_id != current_user.id
        return render file: "#{Rails.root}/public/404.html", status: :not_found, layout: false
      end
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:original_link, :category, :password, :expiration)
    end

    def redirect_params
      params.permit(:slug)
    end

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index

  end
end

app/helpers/about_us_helper.rb
module AboutUsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def link_url(link)
    "#{root_url}l/#{link.slug}"
  end

end

app/views/about_us/index.html.erb
<h1>Acerca de Chq.to</h1>
<p>Chq.to es una app web desarrollada por el alumno Joaquin Tartaruga, para la materia de Taller Tecnologico de Ruby</p>

app/views/accesses/_access.html.erb
<div id="<%= dom_id access %>">
</div>

app/views/accesses/filtered_accesses.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accesses</h1>

<div id="accesses">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Ip_Origen</th>
      <th scope="col">Fecha</th>
    </tr>
    </thead>
  <tbody>
    <% @filtered_accesses.each do |access| %>
    <tr>
        <td><%= access.ip %></td>
        <td><%= access.created_at %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
  
</div>

<button onclick="goBack()">Back to Accesses</button>

<script>
  function goBack() {
    window.history.back();
  }
</script>

app/views/accesses/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Accesses</h1>

<%= form_with(url: filtered_access_path(@link_id), method: :post) do |form| %>
  <div class="mb-3">
    <%= form.select :filter_type, options_for_select(['Por Ip', 'Por fechas'], selected: 'Por Ip'), {}, class: 'form-select' %>
  </div>

  <div class="mb-3 input-ip" style="display: block;">
    <%= form.text_field :ip, class: 'form-control', placeholder: 'Ingresa una IP' %>
  </div>

  <div class="mb-3 input-dates" style="display: none;">
    <%= form.date_field :fecha_inicio, class: 'form-control', placeholder: 'Fecha de inicio' %>
    <%= form.date_field :fecha_fin, class: 'form-control', placeholder: 'Fecha de fin' %>
  </div>

  <%= form.submit 'Buscar', class: 'btn btn-primary' %>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const filterTypeSelect = document.querySelector('select[name="filter_type"]');
    const inputIp = document.querySelector('.input-ip');
    const inputDates = document.querySelector('.input-dates');

    filterTypeSelect.addEventListener('change', (event) => {
      const selectedOption = event.target.value;

      if (selectedOption === 'Por Ip') {
        inputIp.style.display = 'block';
        inputDates.style.display = 'none';
      } else if (selectedOption === 'Por fechas') {
        inputIp.style.display = 'none';
        inputDates.style.display = 'block';
      }
    });
  });
</script>


<div id="accesses">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">Ip_Origen</th>
      <th scope="col">Fecha</th>
    </tr>
    </thead>
  <tbody>
    <% @accesses.each do |access| %>
    <tr>
        <td><%= access.ip %></td>
        <td><%= access.created_at %></td>
    </tr>
    <% end %>
  </tbody>
  </table>
  
</div>

<%= link_to "Back to Links", links_path %>

app/views/contact/index.html.erb
<h1>Informacion de Contacto</h1>
<p><strong>Email:</strong> joaco200127@gmail.com</p>
<p><strong>Telefono:</strong> 2214344908</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Sym</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <%= link_to "Inicio", "/", class: "nav-link" %>
              <%= link_to "Acerca de", about_us_index_path, class: "nav-link" %>
              <%= link_to "Contacto", contact_index_path, class: "nav-link" %>
              <%= link_to "ShortLinks", links_path, class: "nav-link" %>
              <% if user_signed_in? %>
                <%= button_to "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "nav-link" %>
                <%= link_to "Mi Perfil", edit_user_registration_path, class: "nav-link" %>
                <%= link_to "Crear ShortLink", new_link_path, class: "nav-link" %>
                <%= link_to "Mis ShortLinks", my_links_path, class: "nav-link" %>
              <% else %>
                <%= link_to "Iniciar Sesion", new_user_session_path, class: "nav-link" %>
                <%= link_to "Registrarse", new_user_registration_path, class: "nav-link" %>
              <% end %>
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <div class="container">
        <div class="row">
          <div class="col d-flex justify-content-start">
            <div>
              <p class="notice"><%= notice %></p>
              <p class="alert"><%= alert %></p>
              <%= yield %>
            </div>
          </div>
        </div>
      </div>
        <br><br>
  
      <div class="container bg-light w-100">
        <div class="row">
          <div class="col d-flex justify-content-center">
            <div>
              <p>© 2023 JoacoCorp. Todos los derechos reservados.</p>
            </div>
          </div>
        </div>
      </div>    

    </main>

  </body>
</html>

app/views/layouts/index.html.erb
<h1>INDEX</h1> 

app/views/links/_form.html.erb
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :original_link %>
    <%= form.text_field :original_link %>
  </div>

  <br>
  
 <script type="text/javascript">
    document.addEventListener('DOMContentLoaded', function() {
      let select = document.getElementById('opciones'); 

      select.addEventListener('change', function() {
        let privado = document.getElementById('privado');
        let temporal = document.getElementById('temporal');
        if (this.value === 'Temporal') {
          temporal.style.display = 'block';
          privado.style.display = 'none';
        } else {
          if (this.value === 'Privado') {
            privado.style.display = 'block';
            temporal.style.display = 'none';
          } else {
            privado.style.display = 'none';
            temporal.style.display = 'none';
          }
        }
      });
    });
  </script>

  <div class="field">
    <%= label_tag(:category, "Seleccione el tipo de link") %>
    <%= form.select :category, options_for_select(Category.all.map { |c| [c.name] }), {}, { id: 'opciones' } %>
  </div>
  <br>


  <div class="field" id="privado" style="display:none;">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <br>

  <div class="field" id="temporal" style="display:none;">
    <%= form.label :expiration %>
    <%= form.datetime_local_field  :expiration %>
  </div>
  <br>

  <div>
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/links/_link.html.erb
<div id="<%= dom_id link %>">
  <tr>
      <th scope="row"><%= link.id %></th>
      <td><%= link.original_link %></td>
      <td><%= link_to "#{link_url(link)}", "/l/#{link.slug}" %></td>
      <td><%= link.category %></td>
      <% if link.accesses.any? %>
        <td><%= link.today_access %></td>
        <td><%= link.total_access %></td>
      <% else %>
        <td><%= 0 %></td>
        <td><%= 0 %></td>
      <% end %>
      <% if user_signed_in? and link.user_id == current_user.id %>
        <td class="btn btn-primary"><%= link_to 'Ver accesos', accesses_path(link.id) %></td>
        <td class="btn btn-success"><%= link_to 'Editar', edit_link_path(link) %></td>
        <td class="btn btn-danger"><%= button_to 'Borrar', link, method: :delete %></td>
      <% end %>
    </tr>
</div>

app/views/links/edit.html.erb
<h1>Editing link</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/filtered_links.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Original</th>
      <th scope="col">ShortLink</th>
      <th scope="col">Categoria</th>
      <th scope="col">Accesos Diarios</th>
      <th scope="col">Total Accesos</th>
    </tr>
    </thead>
  <tbody>
    <% @filtered_links.each do |link| %>
      <tr>
        <td><%= link.id %></td>
        <td><%= link.original_link %></td>
        <td><%= link_to "#{link_url(link)}", "/l/#{link.slug}" %></td>
        <td><%= link.category %></td>
        <% if link.accesses.any? %>
            <td><%= link.today_access %></td>
            <td><%= link.total_access %></td>
        <% else %>
            <td><%= 0 %></td>
            <td><%= 0 %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
  </table>
</div>

<button onclick="goBack()">Back to Links</button>

<script>
  function goBack() {
    window.history.back();
  }
</script>

app/views/links/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<%= form_with(url: filtered_link_path, method: :post) do |form| %>

  <div class="mb-3 input-ip" style="display: block;">
    <%= form.text_field :ip, class: 'form-control', placeholder: 'Ingresa un Link' %>
  </div>

  <%= form.submit 'Buscar', class: 'btn btn-primary' %>
<% end %>

<div id="links">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Original</th>
      <th scope="col">ShortLink</th>
      <th scope="col">Categoria</th>
      <th scope="col">Accesos Diarios</th>
      <th scope="col">Total Accesos</th>
    </tr>
    </thead>
  <tbody>
      <% @links.each do |link| %>
        <%= render link %>
      <% end %>
  </tbody>
  </table>
</div>

app/views/links/input_password.html.erb
<h1>Ingresa la contraseña</h1>

<%= form_with(url: verify_password_link_path, method: :post) do |form| %>

  <div>
    <%= form.label :password, 'Contraseña:' %>
    <%= form.password_field :password %>
  </div>

  <%= form.submit 'Ingresar' %>
<% end %>

app/views/links/my_links.html.erb
<p style="color: green"><%= notice %></p>

<h1>Links</h1>

<div id="links">
  <table class="table table-striped">
    <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Original</th>
      <th scope="col">ShortLink</th>
      <th scope="col">Categoria</th>
      <th scope="col">Accesos Diarios</th>
      <th scope="col">Total Accesos</th>
    </tr>
    </thead>
  <tbody>
      <% @links.each do |link| %>
        <%= render link %>
      <% end %>
  </tbody>
  </table>
</div>

app/views/links/new.html.erb
<h1>Crea un ShorLink</h1>

<%= render "form", link: @link %>

<br>

<div>
  <%= link_to "Back to links", links_path %>
</div>

app/views/links/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @link %>

<div>
  <%= link_to "Edit this link", edit_link_path(@link) %> |
  <%= link_to "Back to links", links_path %>

  <%= button_to "Destroy this link", @link, method: :delete %>
</div>

app/views/main/index.html.erb
<% if user_signed_in? %>
    <h1>Bienvenido <%= current_user.username %></h1>
<% else %>
    <h1>Bienvenido a Chq.to</h1>
<% end %>
<p>En esta pagina podras recortar una URL. Un acortador de URL es un tipo de servicio software que permite usar URL cortas las cuales redirigen a la URL original. El objetivo de este tipo de servicios es hacer la URL más manejable y fácil de compartir y recordar.</p>